"#version 300 es\n"
"precision mediump float;\n"
"in vec2 TexCoord;\n"
"uniform sampler2D texture1;\n"
"out vec4 FragColor;\n"
"\n"
"void main() {\n"
"    FragColor = texture(texture1, vec2(TexCoord.x, 1.0 - TexCoord.y));\n"
"}\n"
