"#version 300 es\n"
"layout (location = 0) in vec2 vPosition;\n"
"layout (location = 1) in vec2 vTexCoord;\n"
"\n"
"uniform mat4 model;\n"
"out vec2 TexCoord;\n"
"\n"
"void main() {\n"
"    gl_Position = model * vec4(vPosition, 0.0, 1.0);\n"
"    TexCoord = vTexCoord;\n"
"}\n"
