#!/bin/bash

export JAVA_HOME=/opt/google/android-studio/jbr

prefix=plug-
modules=(
  pcsx
  fmsx
  fbneo
  mesen
  bsnes
  snes9x
  citra
  melonds
  mgba
  vbam
  vbanext
  sameboy
  pokemini
  geargrafx
  prosystem
  yabause
  beetlesaturn
  mame2003plus
  genesisplusgx
)
rm -rf build/outputs/apk/release
for module in "${modules[@]}"; do
    ./gradlew ":$prefix$module:assembleRelease"
done